# configs/config.yaml

roboflow:
  api_key: "fHjvN0Omsz5XAduuX3xI"
  workspace: "potholedetection-86cjl"
  project: "pothole_segmentation"
  version: 8

training:
  model: "yolov8s-seg.pt"
  epochs: 1
  imgsz: 640
  patience: 15
  batch: 32
  optimizer: "AdamW"
  lr0: 0.0005
  lrf: 0.05
  device: 0
  seed: 42
  mosaic: 0.3
  cos_lr: true
  cache: true